# Generated by Django 4.2.8 on 2025-05-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('group_invite', 'Group Chat Invite'), ('system', 'System Notification')], max_length=20)),
                ('text', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_friend_requests', models.BooleanField(default=True)),
                ('email_group_invites', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_friend_requests', models.BooleanField(default=True)),
                ('push_group_invites', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=True)),
                ('message_sound', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'notification setting',
                'verbose_name_plural': 'notification settings',
                'db_table': 'notification_setting',
            },
        ),
    ]
